### ISSUE TITLE
Convert output tensor to grayscale depth map

### ISSUE THREAD

**Issue by PetervdPerk** [lorenzopapa5/code-2023-sensors#1]
Hi I've been trying to run the [full_int_tfl_model.tflite](https://github.com/lorenzopapa5/code-2023-sensors/blob/main/weights/full_int_tfl_model.tflite) model on a Coral USB TPU accelerator.

But how do I convert the (48, 64, 1) output tensor to a grayscale depth map?

**Comment by lorenzopapa5** [comment]
Hi, you can try the following lines of code. 

```
def plot_depth_map(dm):
    MIN_DEPTH = 0.0
    MAX_DEPTH = min(np.max(dm), np.percentile(dm, 99))

    dm = np.clip(dm, MIN_DEPTH, MAX_DEPTH)
    cmap = plt.cm.plasma_r  # or other colourmap

    return dm, cmap, MIN_DEPTH, MAX_DEPTH
    

depth, cmap_dm, vmin, vmax = plot_depth_map(depth)
plt.imshow(tf.squeeze(DEPTHMAP), cmap=cmap_dm, vmin=vmin, vmax=vmax)
```

**Comment by PetervdPerk** [comment]
Thanks for the example, I've tried to input this image
![bed](https://github.com/lorenzopapa5/code-2023-sensors/assets/6142456/9274c494-17e7-46ec-8a4a-09518802e2bb)
However with your code I'm getting this as a result.
![image](https://github.com/lorenzopapa5/code-2023-sensors/assets/6142456/9c020c28-4327-4a0c-bcc8-8fec01017b8c)
Any suggestions on what I'm doing wrong?

**Comment by lorenzopapa5** [comment]
I think the input image is in a range between [0, 255], try normalizing the input image into [0, 1] range.
`input_image = tensorflow.clip_by_value(rgb_img / 255, 0, 1)`

**Comment by PetervdPerk** [comment]
Thanks! that was the issue I was facing.
![image](https://github.com/lorenzopapa5/code-2023-sensors/assets/6142456/677acdbe-881c-4abf-85fe-34122997baf7)
